version: '3.1'

services:
  scraper:
    build: .
    restart: always
    entrypoint: 'scrapy crawl wikiscraper -s MONGO_URI=mongodb://mongo:27017/'
    depends_on:
      - mongo
    profiles:
      - scraper


  mongo:
    image: mongo
    restart: always
    ports:
     - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    depends_on:
      - mongo